### ISSUE TITLE
Choix du framework

### ISSUE THREAD

**Issue by tduhautb** [SiMDE-Projects/flairsou-api#1]
Possibilités :
* Frameworks basés JS
* Django

**Comment by tduhautb** [comment]
Back : 
* Django 3.1
* Django 3.2 LTS depuis avril 2021, donc pas encore dans les paquets mais possbilité de merger dessus

Front : 
* ReactJS

**Comment by huetremy** [comment]
@MatthieuDecaux pour Dajngo on aime bien et on pense que tu vas pouvoir t'y lancer assez vite, Python ça devrait pas te poser de soucis (c'est du python version simple, les trucs compliqués c'est le framework qui le fait héhé).
Par contre on sera obligés de changer de langage pour le front, donc JS, et là le chois en gros c'est React/Angular/Vue, React pas compliqué à appréhender et je connais donc on partirait là dessus.
