### ISSUE TITLE
Modèle Entité

### ISSUE THREAD

**Issue by tduhautb** [SiMDE-Projects/flairsou-api#10]
```
Entité (
    #nom : string unique
    utiliseCP : bool
    parent => Entité nullable
)
```

**Comment by huetremy** [comment]
Je viens de penser à un truc. 
Les entités (qui dans le cas général sont des entités indéterminées, dans le cas BDE-UTC des assos) seront récupérées depuis le portail (dans le cas BDE).
Du coup, faudrait que leur clef soit la même que celle du portail, donc a priori un UUID, éventuellement le login de l'asso :)

**Comment by tduhautb** [comment]
Hmm... Comment est-ce qu'on pourrait faire ça de façon générique, histoire que ça puisse facilement s'adapter à d'autres systèmes ?

**Comment by huetremy** [comment]
> Hmm... Comment est-ce qu'on pourrait faire ça de façon générique, histoire que ça puisse facilement s'adapter à d'autres systèmes ?

Le plus simple à mon sens c'est d'ajouter une PK uuid aux entités dans tous les cas. Dans le cas portail, ça correspondra à l'UUID sur le portail, dans le cas général, ça sera juste une clef artificielle

**Comment by tduhautb** [comment]
J'ai ajouté ça, par contre la question qui me vient maintenant c'est comment on gère l'authentification ? Parce que les gens vont se connecter sur des comptes utilisateurs, pas directement sur des comptes entité... comment on va faire le lien dans tout ça avec le système d'auth de Django ? Est-ce qu'il faut rajouter un modèle d'utilisateur quelque part ?

**Comment by huetremy** [comment]
Pour la gestion de l'authentification, ça passera par le back et le portail : via le back, on se log sur le portail (oauth2).
Le portail nous renvoie un Token qui nous permet ensuite de faire des requêtes, c'est la seule chose qui représente un utilisateur pour nous, et donc c'est dans la session mais c'est pas en base.
Ensuite on peut se servir de ce token pour vérifier les droits de l'utilisateur : on demande au portail de nous donner les associations et posts de cet utilisateur (donc de ce token) ce qui nous permet de déduire les droits
