### ISSUE TITLE
Bug: montant d'une transaction 

### ISSUE THREAD

**Issue by pierreadorni** [SiMDE-Projects/flairsou-api#143]
On m'a signalé un problème d'enregistrement du montant d'une transaction:
la transaction en question s'enregistrerait toujours comme valant 1ct de moins que ce que l'utilisateur rentre.
vidéo à l'appui:

[video](https://user-images.githubusercontent.com/35078720/161012057-2306092e-6cd3-4369-b525-94427f220e4d.mp4)

**Comment by tduhautb** [comment]
Ça a l'air d'être un problème de flottant :

![erreur_flairsou](https://user-images.githubusercontent.com/43524285/161045795-4a296b02-4cb8-49b3-9735-b30ae9119ab2.png)
