### ISSUE TITLE
Comptes virtuels

### ISSUE THREAD

**Issue by huetremy** [SiMDE-Projects/flairsou-api#20]
On a ressorti ça de la review avec @MatthieuDecaux  mais comme ça change rien au code de la PR j'ouvre en issue.

Le fonctionnement des comptes virtuels tel que défini dans la conception implique qu'un compte qui a déja en des transactions ne peut pas devenir virtuel. Cela pose un soucis de flexibilité : par exemple, si le bureau d'un semestre n crée un compte Dépenses/fournisseurs et y ajoute une transaction, alors le bureau du semestre n+i ne peut pas se dire « c'est nul, on aimerait faire plus de séparation et mettre dans Dépenses/fournisseurs/JP ».

On propose donc une adaptation telle que : 
- Un compte non virtuel peut devenir virtuel **s'il n'a aucune opération non rapprochée**.

Le solde d'un compte virtuel n'est alors plus « somme des soldes des sous comptes » mais « somme des soldes des sous-comptes + solde au dernier rapprocement *(éventuellement nul)* »

On peut imaginer deux scénarii de changement : 
- On laisse à l'utililsateur la possibilité de changer lui-même
- On ne peut le faire que nous-même.
Perso pas d'objection à laisser à l'utilisateur la possibilité de le faire.

**Comment by tduhautb** [comment]
D'accord avec le souci de flexibilité.

Est-ce qu'on ne peut pas juste prévoir une fonction qui transforme un compte non-virtuel en compte virtuel et qui fait : 
* définition d'un sous-compte de rattachement
* déplacement de toutes les transactions du compte de base vers le sous-compte de rattachement
* flag du compte de base virtuel

Comme ça ça évite de se compliquer la vie avec le calcul des soldes, et ça règle le problème de flexibilité. Par rapport aux éventuels rapprochements, on peut soit transférer les rapprochements existants sur le sous-compte soit purement et simplement les supprimer. Après, d'un autre côté, ça n'a pas vraiment de sens de réorganiser un compte si il a des rapprochements parce que tu rapproches par rapport à un document qui fixe ta structure, et en pratique on ne rapproche pas les comptes de dépenses / recettes donc bon...

**Comment by huetremy** [comment]
Ok, ça me paraît bien !
