### ISSUE TITLE
Filtrage des comptes par book

### ISSUE THREAD

**Issue by tduhautb** [SiMDE-Projects/flairsou-api#30]
J'ai regardé pour filtrer les comptes par `book` et en fait peut-être qu'on a fait un mauvais choix au départ. Actuellement un compte est rattaché soit à un parent, soit à un livre, mais pas les deux. Du coup, si on veut récupérer tous les comptes associés à un livre, on doit faire plusieurs requêtes, de l'ordre de la profondeur de l'arbre de comptes.

J'ai regardé au niveau des structures d'arbre en SQL, y'a des techniques (https://www.sitepoint.com/hierarchical-data-database-2/) mais l'inconvénient que j'y vois c'est que tous les comptes du même arbre doivent être numérotés de façon continue. Ça veut dire que si on rajoute un compte au milieu, il faut renuméroter tous les comptes de la table, ça se fait mais c'est un peu relou.

Finalement je me dis qu'on pourrait juste garder le `book` dans tous les comptes (le passer non null du coup), avec la contrainte (API au moins, SQL si on trouve comment) que le `book` d'un compte est le même que celui de son père. Ça permet de simplifier les requêtes de récupération de l'ensemble des comptes d'un livre, sans ajouter trop de redondance et sans trop compliquer les choses.

@huetremy un avis ?

**Comment by huetremy** [comment]
Ça me paraît pas déconnant de faire comme ça :)
Ça rajoute pas spécialement de contrainte (disons qu'on en ajouté une mais on enlève de Book ou Parent null) et effectivement ça nous simplifiera la vie :)
