### ISSUE TITLE
Création d'un nouveau compte

### ISSUE THREAD

**Issue by tduhautb** [SiMDE-Projects/flairsou-api#65]
Mise en place des éléments front pour envoyer la requête de création de compte à l'API

**Comment by mael-belval** [comment]
- Je ne vois pas d'issue sur les book en front, besoin de les créer aussi non ?
- Sur le swagger, pour post /api/accounts/, dans le body d'exemple, je vois dans le body d'exemple un champs associated_entity, pas présent dans la description. Je me base sur l'exemple ou la description ?

**Comment by tduhautb** [comment]
- les books sont créés automatiquement a partir de la liste des assos récupérée du portail, comme ça on a systématiquement un livre par asso
- le champ associated_entity permet d'autoriser une autre asso à voir un compte, j'ai peut-être pas mis à jour la description mais il faut prendre en compte le champ oui. C'est un système pour les clubs qui n'ont pas de compte mais qui pourront visualiser les transactions qui les concernent au niveau du pôle

**Comment by mael-belval** [comment]
"les books sont créés automatiquement" => dans ce cas, quel intérêt des requêtes autre que GET sur /api/books/[...] ?

**Comment by mael-belval** [comment]
Pour rebondir sur associated_entity, le champ est bien facultatif du coup ?

**Comment by tduhautb** [comment]
> "les books sont créés automatiquement" => dans ce cas, quel intérêt des requêtes autre que GET sur /api/books/[...] ?

C'est parce que au départ j'ai tout créé pour toutes les entités, mais il y avait effectivement des choses en trop, que je suis justement en train de supprimer ;) => #83

**Comment by tduhautb** [comment]
> Pour rebondir sur associated_entity, le champ est bien facultatif du coup ?

Oui le champ est facultatif, et il faudra faire un petit truc pour récupérer la liste des assos qu'on peut mettre ici, c'est à dire la liste des sous-assos de l'entité.

**Comment by mael-belval** [comment]
[MR 80](https://github.com/SiMDE-Projects/flairsou-api/pull/80)
